version: '3'

services:
    backend:
        image: h4s-backend
        build:
            context: ./backend
        restart: always
    frontend:
        image: h4s-frontend
        build:
            context: ./frontend
        restart: always
    proxy:
        image: nginx:1.19.10-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8080:80
        restart: always
