FROM node:15.14.0-alpine3.10

WORKDIR /usr/src/app

COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./frontend/ ./

RUN yarn build

ENV version=production

FROM python:3.8

WORKDIR /usr/src/app

ENV PORT 8080

COPY ./backend .

RUN apt update && apt install build-essential
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

COPY --from=0 /usr/src/app/build /usr/src/app/static

EXPOSE ${PORT}/tcp

CMD ["./run.sh"]

LABEL Version dev
LABEL Name h4s

